name: papyrus
version: 0.1.1
description: A Dart documentation generator
dependencies:
  analyzer: '>=0.22.0 <0.23.0'
  args: '>=0.12.0 <0.13.0'
dev_dependencies:
  grinder: any
  unittest: any
executables:
  papyrus:
