
library html_gen;

import 'package:intl/intl.dart';

import 'css.dart';

class HtmlGenerator {
  StringBuffer buffer = new StringBuffer();  
  bool startOfLine = true;
  List<String> tags = [];
  
  HtmlGenerator() {
    println('<!DOCTYPE html>');
    println();
    println('<!-- generated by papyrus on '
       '${new DateFormat.yMd().format(new DateTime.now())} -->');
    println();
  }
  
  void start([String title]) {
    startTag('html');
    startTag('head');
    
    println('<meta charset="utf-8">');
    println('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
    
    if (title != null) {
      println('<title>${title}</title>');
    }
    
    println('<link href="${css.getCssName()}" rel="stylesheet" media="screen">');
    println("""<style>
.left-nav {
  margin-top: 20px;
}

.left-nav > .active > a, .left-nav > .active > a:hover, .left-nav > .active > a:focus {
  color: #ffffff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
  background-color: #0088cc;
}

.icon-chevron-right {
  float: right;
  margin-top: 2px;
  margin-right: -6px;
  opacity: .25;
}

.active .icon-chevron-right, .active a:hover .icon-chevron-right {
  background-image: url(glyphicons-halflings-white.png);
  opacity: 1;
}
</style>""");
    
    // head
    endTag();
    
    startTag('body');
  }
  
  void startTag(String tag, [String attributes]) {
    if (attributes != null) {
      println('<${tag} ${attributes}>');
    } else {
      println('<${tag}>');
    }
    
    tags.add(tag);
  }
  
  void tag(String tag, [String content]) {
    if (content != null) {
      println('<$tag>$content</$tag>');      
    } else {
      println('<$tag/>');
    }
  }
  
  void endTag() {
    String tag = tags.removeLast();
    
    println('</${tag}>');
  }
  
  void end() {
    // body
    endTag();
    
    // html
    endTag();
  }
  
  String get indent {
    StringBuffer buf = new StringBuffer();
    for (int i = 0; i < tags.length; i++) {
      buf.write('\t');
    }
    return buf.toString();
  }
  
  String toString() {
    return buffer.toString();
  }
  
  void print(String str) {
    if (startOfLine) {
      buffer.write(indent);
      startOfLine = false;
    }
    
    buffer.write(str);
  }
  
  void println([String str]) {
    if (str == null) {
      print('\n');
    } else {
      print('${str}\n');
    }
    
    startOfLine = true;
  }

}
