
library html_gen;

import 'package:intl/intl.dart';

import 'css.dart';

class HtmlGenerator {
  StringBuffer buffer = new StringBuffer();  
  bool startOfLine = true;
  List<String> tags = [];
  
  HtmlGenerator() {
    writeln('<!DOCTYPE html>');
    writeln();
    writeln('<!-- generated by papyrus on '
       '${new DateFormat.yMd().format(new DateTime.now())} -->');
    writeln();
  }
  
  void start({String title, String cssRef}) {
    startTag('html');
    startTag('head');
    
    writeln('<meta charset="utf-8">');
    writeln('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
    
    if (title != null) {
      writeln('<title>${title}</title>');
    }
    
    if (cssRef != null) {
      writeln('<link href="${cssRef}" rel="stylesheet" media="screen">');
    }
    
    writeln("""<style>
.left-nav {
  margin-top: 20px;
}

.left-nav > .active > a, .left-nav > .active > a:hover, .left-nav > .active > a:focus {
  color: #ffffff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
  background-color: #0088cc;
}

.icon-chevron-right {
  float: right;
  margin-top: 2px;
  margin-right: -6px;
  opacity: .25;
}

.active .icon-chevron-right, .active a:hover .icon-chevron-right {
  background-image: url(glyphicons-halflings-white.png);
  opacity: 1;
}

.indent {
  margin-left: 1em;
  margin-bottom: 0.5em;
}
</style>""");
    
    // head
    endTag();
    
    startTag('body');
  }
  
  void startTag(String tag, {String attributes, bool newLine: true}) {
    if (attributes != null) {
      if (newLine) {
        writeln('<${tag} ${attributes}>');
      } else {
        write('<${tag} ${attributes}>');
      }
    } else {
      if (newLine) {
        writeln('<${tag}>');
      } else {
        write('<${tag}>');
      }
    }
    
    tags.add(tag);
  }
  
  void tag(String tag, {String attributes, String contents}) {
    if (attributes != null) {
      if (contents != null) {
        writeln('<$tag $attributes>$contents</$tag>');      
      } else {
        writeln('<$tag $attributes></$tag>');
      }
    } else {
      if (contents != null) {
        writeln('<$tag>$contents</$tag>');      
      } else {
        writeln('<$tag></$tag>');
      }
    }
  }
  
  void endTag() {
    String tag = tags.removeLast();
    
    writeln('</${tag}>');
  }
  
  void end() {
    // body
    endTag();
    
    // html
    endTag();
  }
  
  String get indent {
    StringBuffer buf = new StringBuffer();
    for (int i = 0; i < tags.length; i++) {
      buf.write('\t');
    }
    return buf.toString();
  }
  
  String toString() {
    return buffer.toString();
  }
  
  void write(String str) {
    if (startOfLine) {
      buffer.write(indent);
      startOfLine = false;
    }
    
    buffer.write(str);
  }
  
  void writeln([String str]) {
    if (str == null) {
      write('\n');
    } else {
      write('${str}\n');
    }
    
    startOfLine = true;
  }

}
